### ISSUE TITLE
Newly created documents cannot be loaded individually until page is refreshed

### ISSUE THREAD

**Issue by WolfElkan** [WolfElkan/CDJ-Angular-Friends#2]
The project is almost done.  The only bug left is that when you create a new friend, they don't have an `_id` since that is assigned on the back end.  Angular doesn't mind this, and displays them on the index page anyway, but if you try to `edit` or `show` them, you get redirected back to the `index` page, since the backend `_id`'s are used in page navigation.

My solution to this was to create a temporary `_id` for every newly-created friend.  This would allow for page navigation, and would be replaced by the actual backend `_id` when the page was reloaded.  This succeeded in allowing page navigation, and the proper friend even seems to be loading, but is not displayed on the page.

**Comment by hermanj13** [comment]
on the front end, for the edit link if you direct it to the edit/{{friend._id}} wouldn't that work fine? angular should be able to populate it everytime you populate a new friend
